# Generated by Django 3.2.7 on 2021-09-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=25)),
                ('address', models.JSONField()),
                ('email', models.EmailField(max_length=254)),
                ('Phone_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('address', models.JSONField()),
                ('email', models.EmailField(max_length=254)),
                ('Phone_no', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=30)),
                ('Company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Seller.company')),
            ],
        ),
    ]
