# Generated by Django 3.2.7 on 2021-09-27 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=25)),
                ('p_type', models.CharField(max_length=25)),
                ('p_dimension', models.JSONField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.employee')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.company')),
            ],
        ),
    ]
